services:
  - type: web
    name: api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: MODE
        value: api
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      - key: MIGRATION_ENABLED
        value: 'true'
      - key: PGHOST
        fromDatabase:
          name: difyDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: difyDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: difyDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: difyDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: difyDB
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - key: CELERY_BROKER_URL
        value: redis://:${redis.PASSWORD}@${redis.HOST}:${redis.PORT}/1
      - key: VECTOR_STORE
        value: qdrant
      - key: QDRANT_URL
        value: https://98d0bf03-d08e-40d7-880c-63984f247731.us-east4-0.gcp.cloud.qdrant.io:6333
      - key: QDRANT_API_KEY
        value: NIFUqE3BMS2A84QjT-nbR6rcsPcn0whRt0av4mBGihIcVNgFKBAxXA
      - key: SENTRY_DSN
        value: 'https://4d5241867f0d2ed25ac913316e167a61@o190918.ingest.us.sentry.io/4506889664462848'
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: 1.0

  - type: worker
    name: worker
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: MODE
        value: worker
      - key: LOG_LEVEL
        value: INFO
      - key: SECRET_KEY
        value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      - key: MIGRATION_ENABLED
        value: 'true'
      - key: PGHOST
        fromDatabase:
          name: difyDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: difyDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: difyDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: difyDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: difyDB
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - key: CELERY_BROKER_URL
        value: redis://:${redis.PASSWORD}@${redis.HOST}:${redis.PORT}/1
      - key: VECTOR_STORE
        value: qdrant
      - key: QDRANT_URL
        value: https://98d0bf03-d08e-40d7-880c-63984f247731.us-east4-0.gcp.cloud.qdrant.io:6333
      - key: QDRANT_API_KEY
        value: NIFUqE3BMS2A84QjT-nbR6rcsPcn0whRt0av4mBGihIcVNgFKBAxXA
      - key: SENTRY_DSN
        value: 'https://4d5241867f0d2ed25ac913316e167a61@o190918.ingest.us.sentry.io/4506889664462848'
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: 1.0

  - type: redis
    name: lightning
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

  - type: web
    name: web
    env: docker
    dockerfilePath: ./web/Dockerfile
    dockerContext: ./web

databases:
  - name: difyDB
    plan: starter